version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "kotlinCoroutinesVersion"
      versions:
        - "*-native-mt"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
