version = 1

[merge]
method = "squash"
prioritize_ready_to_merge = true

[approve]
auto_approve_usernames = ["dependabot-preview", "gnarea"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
